version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=badania2023
    ports:
      - "5432:5432"
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=badanka@agh.pl
      - PGADMIN_DEFAULT_PASSWORD=badania2023
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pg_network

networks:
  pg_network: