version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=badania2023
      - POSTGRES_DB=AutomaticSteditor
    ports:
      - "5432:5432"
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=badanka@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=badania2023
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pg_network

networks:
  pg_network:
